//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeltaImpuls.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public System.Guid ID { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public System.Guid role_id { get; set; }
    
        public virtual role role { get; set; }
    }
}
